version: '3'

services:
    timemachine:
        image: odarriba/timemachine
        volumes:
            - "/var/opt/timemachine/timemachine:/timemachine"
        ports:
            - "548:548"
            - "636:636"
        restart:
            unless-stopped
